name: Multi-Platform Docker Build, Test, and Push

on:
  push:
    branches:
      - main
      - '**'    # all branches
    tags:
      - 'v*'

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU for multi-arch emulation
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi
          echo "BRANCH_OR_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build and push tgpt-code-interpreter image (branch/tag)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ucsd-ets/tgpt-code-interpreter:${{ steps.get_version.outputs.BRANCH_OR_TAG }}
          cache-from: type=registry,ref=ghcr.io/ucsd-ets/tgpt-code-interpreter:buildcache
          cache-to: type=registry,ref=ghcr.io/ucsd-ets/tgpt-code-interpreter:buildcache,mode=max

      - name: Build and push tgpt-code-executor image (branch/tag)
        uses: docker/build-push-action@v6
        with:
          context: ./executor
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ucsd-ets/tgpt-code-executor:${{ steps.get_version.outputs.BRANCH_OR_TAG }}
          cache-from: type=registry,ref=ghcr.io/ucsd-ets/tgpt-code-executor:buildcache
          cache-to: type=registry,ref=ghcr.io/ucsd-ets/tgpt-code-executor:buildcache,mode=max

      - name: Tag and push version-specific images
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker pull ghcr.io/ucsd-ets/tgpt-code-interpreter:${{ steps.get_version.outputs.BRANCH_OR_TAG }}
          docker tag ghcr.io/ucsd-ets/tgpt-code-interpreter:${{ steps.get_version.outputs.BRANCH_OR_TAG }} ghcr.io/ucsd-ets/tgpt-code-interpreter:${{ steps.get_version.outputs.VERSION }}
          docker push ghcr.io/ucsd-ets/tgpt-code-interpreter:${{ steps.get_version.outputs.VERSION }}
          docker pull ghcr.io/ucsd-ets/tgpt-code-executor:${{ steps.get_version.outputs.BRANCH_OR_TAG }}
          docker tag ghcr.io/ucsd-ets/tgpt-code-executor:${{ steps.get_version.outputs.BRANCH_OR_TAG }} ghcr.io/ucsd-ets/tgpt-code-executor:${{ steps.get_version.outputs.VERSION }}
          docker push ghcr.io/ucsd-ets/tgpt-code-executor:${{ steps.get_version.outputs.VERSION }}

      - name: Run repository build script
        run: bash scripts/run-build.sh

      - name: Create KinD cluster for integration tests
        uses: engineerd/setup-kind@v0.6.2
        with:
          version: v0.24.0

      - name: Wait for Kubernetes API
        run: kubectl cluster-info

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: latest

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run end-to-end tests
        run: |
          nohup bash -c 'poetry run poe run' &
          sleep 10
          poetry run poe test
